baseURL = "https://mapping-money.com/"
languageCode = "en-us"
title = "Mapping Money"
theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.logo]
src = "/img/logo.png"

[params.reveal_hugo]
custom_theme = "reveal-hugo/themes/robot-lung.css"

